config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  def change
   
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    Game.create(game_params)
    redirect_to root_path
  end

  def game_params
    params.require(:game).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<% @games.each do |game| %>
  <div class="booyah-box col-10 offset-1">
    <h2><%= game.name %></h2><br />
    <p><%= game.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/games/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>What is your favorite game?</h1>
  <%= simple_form_for @game do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>

    <h1>Our Favorite Games</h1>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <li>
      <%= link_to 'New Game', new_game_path, class: 'nav-link'%>
    </li>
    <%= yield %>
  </body>
</html>